services:
  python-device-discover:
    build: .
    container_name: python-device-discover
    ports:
      - "3001:3001"
    network_mode: host
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
